"""add message_type to chat_history

Revision ID: 316e4a439d18
Revises: 3b1f7d8d9932
Create Date: 2026-02-11 23:11:27.017521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316e4a439d18'
down_revision: Union[str, Sequence[str], None] = '3b1f7d8d9932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('message_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'message_type')
    # ### end Alembic commands ###
