"""Add progress tracking fields to clusters

Revision ID: 9dfeffc1ffb3
Revises: f4c2e8d7987c
Create Date: 2026-02-08 15:53:52.347200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfeffc1ffb3'
down_revision: Union[str, Sequence[str], None] = 'f4c2e8d7987c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_clusters', sa.Column('confidence_delta', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('concept_clusters', sa.Column('delta_since', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subject_clusters', sa.Column('learning_delta', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('subject_clusters', sa.Column('delta_since', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject_clusters', 'delta_since')
    op.drop_column('subject_clusters', 'learning_delta')
    op.drop_column('concept_clusters', 'delta_since')
    op.drop_column('concept_clusters', 'confidence_delta')
    # ### end Alembic commands ###
