"""Add summary_up_to_message_id to ChatSession

Revision ID: 9eb022086ed9
Revises: 227f5f8ce627
Create Date: 2026-01-08 23:57:17.868887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb022086ed9'
down_revision: Union[str, Sequence[str], None] = '227f5f8ce627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary_up_to_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary_up_to_message_id')
    # ### end Alembic commands ###
