"""add refresh_tokens table

Revision ID: 9f2f138b8638
Revises: 9eb022086ed9
Create Date: 2026-01-10 22:05:34.314307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2f138b8638'
down_revision: Union[str, Sequence[str], None] = '9eb022086ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expires_at')
    # ### end Alembic commands ###
