"""Add confidence_score to ConceptCluster

Revision ID: c2622e9fdbfa
Revises: 696eb8e82a70
Create Date: 2026-02-03 23:35:22.544673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2622e9fdbfa'
down_revision: Union[str, Sequence[str], None] = '696eb8e82a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_clusters', sa.Column('confidence_score', sa.Float(), nullable=False, server_default="0.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_clusters', 'confidence_score')
    # ### end Alembic commands ###
